spring:
  application:
    name: serviceedu
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址
logging:
  level:
    com.atguigu.edu.mapper: debug

